---
title: "final project draft"
author: "Alex Gazzolo"
date: "12/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(rvest)
library(tidycensus)
library(tidytext)
library(nametagger)
library(udpipe)
library(stargazer)
```

Data
```{r}
# code sources: for splitting date column: https://stackoverflow.com/questions/4078502/split-date-data-m-d-y-into-3-separate-columns
# for updating state column IDs: https://stackoverflow.com/questions/53639594/how-to-use-mutate-to-add-column-with-state-names-based-on-the-state-abbreviation
adopt <- read_csv("sac_aggregate_dataset_2019_2021.csv")
covid <- read_csv("us-states-new.csv")
covid$date <- as.Date(covid$date)
covid <- covid %>% mutate(
                 year = as.numeric(format(date, format = "%Y")),
                 month = as.numeric(format(date, format = "%m")),
                 day = as.numeric(format(date, format = "%d")))
covid_yr <- covid %>% group_by(state, year) %>% summarise(cases = sum(cases))
url <- "https://en.wikipedia.org/wiki/U.S._state_and_local_government_responses_to_the_COVID-19_pandemic"
request <- read_html(url)
table <- html_table(request, fill = TRUE)
View(table[[3]])
lockdowns <- table[[3]]
colnames(lockdowns) <- c('State_del',
                         'State',
                         'Emergency_Declared', 
                         'Stay_At_Home_Ordered', 
                         'Stay_At_Home_Lifted',
                         'Masks_Required',
                         'Gatherings',
                         'Travel_Restrictions',
                         'Closures_School',
                         'Closures_Daycare',
                         'Closures_Restaurants',
                         'Closures_Retail',
                         'Sources')
lockdowns <- lockdowns %>% select(!c(State_del, 
                        Gatherings, 
                        Travel_Restrictions, 
                        Closures_School,
                        Closures_Daycare,
                        Closures_Restaurants,
                        Closures_Retail,
                        Sources))
lockdowns <- lockdowns %>% mutate(SAH = ifelse(Stay_At_Home_Ordered == 'No', 0, 1))
lockdowns = lockdowns[-1,]
lockdowns <- lockdowns %>% separate(Stay_At_Home_Ordered, c("Start_Month", "Start_Day")) 
lockdowns <- lockdowns %>% separate(Stay_At_Home_Lifted, c("End_Month", "End_Day"))
lockdowns$Start_Month <- na_if(lockdowns$Start_Month, "No")
lockdowns$End_Month <- na_if(lockdowns$End_Month, "No")
lockdowns$End_Month <- na_if(lockdowns$End_Month, "N")
lockdowns$End_Day <- na_if(lockdowns$End_Day, "a")
lockdowns$End_Day <- na_if(lockdowns$End_Day, "advisory")
lockdowns$year <- 2020
lockdowns$Start_Date <- as.Date(paste(lockdowns$year, lockdowns$Start_Month, lockdowns$Start_Day, sep = "-"),"%Y-%b-%d")
lockdowns$End_Date <- as.Date(paste(lockdowns$year, lockdowns$End_Month, lockdowns$End_Day, sep = "-"),"%Y-%b-%d")
lockdowns$SAH_Duration <- lockdowns$End_Date - lockdowns$Start_Date
lockdown_clean <- lockdowns %>% select(c(State, SAH, Start_Date, End_Date, SAH_Duration))

feline_intake <- c("Intake - Relinquished By Owner Total-Feline", 
                   "Intake - Stray At Large Total-Feline", 
                   "Intake - Transferred In Total-Feline", 
                   "Intake - Owner Intended Euthanasia Total-Feline")
canine_intake <- c("Intake - Relinquished By Owner Total-Canine",
                   "Intake - Stray At Large Total-Canine",
                   "Intake - Transferred In Total-Canine", 
                   "Intake - Owner Intended Euthanasia Total-Canine",
                   "Intakes - Other Intakes Total-Canine")

adopt$feline_intake_total <- adopt$`Intake - Relinquished By Owner Total-Feline` + adopt$`Intake - Stray At Large Total-Feline` + adopt$`Intake - Transferred In Total-Feline` + adopt$`Intake - Owner Intended Euthanasia Total-Feline` + adopt$`Intakes - Other Intakes Total-Feline`
adopt$canine_intake_total <- adopt$`Intake - Relinquished By Owner Total-Canine` + adopt$`Intake - Stray At Large Total-Canine` + adopt$`Intake - Transferred In Total-Canine` + adopt$`Intake - Owner Intended Euthanasia Total-Canine` + adopt$`Intakes - Other Intakes Total-Canine`
adopt$intake_total <- adopt$feline_intake_total + adopt$canine_intake_total
adopt$adoption_total <- adopt$`Live Outcome - Adoption Total-Feline` + adopt$`Live Outcome - Adoption Total-Canine`
adopt_clean <- adopt %>% select(c(State, Year, feline_intake_total, canine_intake_total, intake_total, `Live Outcome - Adoption Total-Feline`, `Live Outcome - Adoption Total-Canine`, adoption_total))

Sys.getenv("CENSUS_API_KEY")
# variables <- load_variables(2020, "pl", cache = FALSE)
state_pop <- get_decennial(geography = "state", 
              variables = c(population = "P1_001N"), 
              year = 2020)
state_pop <- state_pop %>% rename(Population = value) %>%
  select(c(NAME, Population))
adopt_clean <- adopt_clean %>% 
  mutate(State = state.name[match(State, state.abb)])

data <- left_join(adopt_clean, covid_yr, by = c("State" = "state", "Year" = "year"))
data <- left_join(data, state_pop, by = c("State" = "NAME"))
data <- left_join(data, lockdown_clean, by = "State")
# dropping US Territories and adding adoption rate and adoptions per capita
data <- data %>% drop_na(State)
data$adoption_rate <- data$adoption_total/data$intake_total
data$adoption_percap <- data$adoption_total/data$Population
```

Plots
```{r}
# pet adoptions per capita, adoptions vs. cases, adoptions vs. sah, cats v dogs on map
ggplot(data2020, aes(SAH_Duration, adoption_total)) +
  geom_point() +
  geom_abline()

ggplot(data_cases, aes(cases, adoption_total)) +
  geom_point() +
  geom_abline()

state <- tolower(data$State)
map <- map_data("state")
ggplot(data, aes(fill = adoption_total)) +
  geom_map(aes(map_id = state), map = map)
```

Regression
```{r}
data2020 <- data %>% filter(Year == 2020) %>%
  mutate(across(SAH_Duration, ~ ifelse(is.na(.), 0, .)))
data_cases <- data %>% filter(Year != 2019) %>%
  mutate(across(cases, ~ ifelse(is.na(.), 0, .)))
reg_adopt_cases <- lm(adoption_total ~ cases + Population, data = data_cases)
stargazer(reg_adopt_cases, type = "text")
reg_adoptrate_cases <- lm(adoption_rate ~ cases + Population, data = data_cases)
stargazer(reg_adoptrate_cases, type = "text")
reg_adopt_SAH <- lm(adoption_total ~ SAH_Duration + Population, data = data2020)
stargazer(reg_adopt_SAH, type = "text")
reg_adoptrate_SAH <- lm(adoption_rate ~ SAH_Duration + Population, data = data2020)
stargazer(reg_adoptrate_SAH, type = "text")
```

Text Analysis
```{r}
sentiment_nrc <-   
  get_sentiments("nrc") %>%
  rename(nrc = sentiment)

analyze_text <- function(url, css) {
  request <- read_html(url)
  article <- html_nodes(request, css)
text_list <- html_text(article)
text <- paste(text_list, collapse = "") %>% tibble(text = text_list)
word_tokens_url <-     unnest_tokens(text, word_tokens,  text, token = "words")
no_sw_df <- anti_join(word_tokens_url, stop_words, by = c("word_tokens" = "word"))
no_sw_df_sent <- no_sw_df %>%
  left_join(sentiment_nrc, by = c("word_tokens" = "word"))
return(no_sw_df_sent)
}

i2020_aspca <- analyze_text("https://www.aspcapro.org/news/2020/06/10/over-570-groups-complete-7300-adoptions-during-aspca-national-adoption-weekend", ".post__body")
m2020_nyt <- analyze_text("https://www.nytimes.com/2020/05/06/smarter-living/a-guide-for-first-time-pet-owners-during-the-pandemic.html?searchResultPosition=4",".StoryBodyCompanionColumn")
i2021_dvm <- analyze_text("https://www.dvm360.com/view/making-dermatology-cases-more-efficient-in-general-practice", ".mt-3")
i2021_aspca <- analyze_text("https://www.aspcapro.org/resource/new-aspca-survey-vast-majority-dogs-and-cats-acquired-during-pandemic-still-their-homes", ".paragraph--copy")
m2021_sa <- analyze_text("https://www.scientificamerican.com/article/home-alone-the-fate-of-postpandemic-dogs/", "#sa_body > div.opinion-article__wrapper > section.flex-container.container.flex-direction--column-tablet > article")
m2022_wapo <- analyze_text("https://www.washingtonpost.com/business/2022/01/07/covid-dogs-return-to-work/",".font-copy")
# I was not able to scrape this site so I pulled the text instead
#i2022_pfi <- analyze_text("https://www.petfoodindustry.com/articles/11748-pandemic-new-pet-boom-myth-busted-adoptions-lower-2021-22", "/html/body/div[5]/div[2]/div[1]/div[4]/div[1]")
i2022_pfi <- read_file("petfoodindustry2022.txt")
i2022_pfi_word <- tibble(text = i2022_pfi)
i2022_pfi_word <-  unnest_tokens(i2022_pfi_word, word_tokens,  text, token = "words") 
i2022_pfi <- anti_join(i2022_pfi_word, stop_words, by = c("word_tokens" = "word"))
i2022_pfi <- i2022_pfi %>% left_join(sentiment_nrc, by = c("word_tokens" = "word"))


count(m2020_nyt, nrc, sort = TRUE)
count(i2020_aspca, nrc, sort = TRUE)
count(i2021_dvm, nrc, sort = TRUE)
count(i2021_aspca, nrc, sort = TRUE)
count(m2021_sa, nrc, sort = TRUE)
count(m2022_wapo, nrc, sort = TRUE)
count(i2022_pfi, nrc, sort = TRUE)

```

Shiny